### ISSUE TITLE
Drop Python2 support?

### ISSUE THREAD

**Issue by mfeurer** [renatopp/liac-arff#107]
Hey everybody,

given that Python2 has reached the end of its life, maybe it is also time to finally drop Python2 support for liac-arff. This could make maintenance easier, but will also allow us to use new features such as type annotations. Are there any opinions on this?

**Comment by mfeurer** [comment]
CC @jnothman @renatopp @rth

**Comment by jnothman** [comment]
+1

I think the latest py2-friendly release will remain useful. But
maintainability here is a big block against supporting new features. if we
move to Py>=3.5 as a lot of the community has, then we have an opportunity
to simplify the code.

**Comment by rth** [comment]
Yes, I think it would be great! @mfeurer Would you be able to release 2.5.0 (or 2.4.1 not sure) with the current version of master as the last Python 2.7 release?

I can make a PR to remove unnecessary code if we only support Python 3.6+ (Python 3.5 reached end of life last November https://www.python.org/dev/peps/pep-0478/#id4)

**Comment by mfeurer** [comment]
My schedule is currently pretty full. I hope that I can do it late this week or beginning of next week.

**Comment by rth** [comment]
Any chance someone would be able to make a last Python 2.7 release, so that it can be dropped on master?

**Comment by mfeurer** [comment]
Hi, let me just do this now so it's done

**Comment by mfeurer** [comment]
Here we go: https://pypi.org/project/liac-arff/2.5.0/

**Comment by rth** [comment]
Thank you @mfeurer !

**Comment by rth** [comment]
Closing as resolved in https://github.com/renatopp/liac-arff/pull/109

It would have been nice to also create a v2.5.0 git tag on the same commit as the PyPi release..

**Comment by mfeurer** [comment]
Here we go https://github.com/renatopp/liac-arff/releases/tag/v2.5.0
