### ISSUE TITLE
Added to conda

### ISSUE THREAD

**Issue by BastianZim** [renatopp/liac-arff#115]
Hi,

this is more of an FYI than an issue but I just wanted to let you guys know that I added liac-arff to conda-forge so that it can be downloaded with conda.

The repo is here: https://github.com/conda-forge/liac-arff-feedstock

Let me know if anyone of the maintainers here would like to be added as maintainers there or if I should make a PR here to add a badge or install instructions. Otherwise, feel free to just close the issue.

Thanks! 😃

**Comment by mfeurer** [comment]
That's a great addition, thanks a lot! Yes, could you please make me a maintainer just in case? Also, a note in the docs here would be good I guess.

CC @renatopp

**Comment by BastianZim** [comment]
My pleasure! Of course, I have added you as a maintainer in https://github.com/conda-forge/liac-arff-feedstock/pull/1 and #116 should add conda. Let me know if you prefer a different style there.

**Comment by mfeurer** [comment]
Thanks a lot @BastianZim

**Comment by BastianZim** [comment]
Happy to help!
