### ISSUE TITLE
ARFF attribute naming specification changed

### ISSUE THREAD

**Issue by joaquinvanschoren** [renatopp/liac-arff#24]
Hi Renato, 

The specification of ARFF has recently changed to allow a wider range of attribute names. More specifically, attributes are now allowed to start with numbers (in fact any character except control characters and '{', '}', ',', or '%': http://weka.wikispaces.com/ARFF+%28stable+version%29

It would be great if liac-arff could be updated to reflect this. We are using liac-arff for python clients for OpenML.org and some of our datasets (those that have attributes starting with numbers) cannot be parsed by liac-arff because of this reason.

Many thanks!

Sincerely,
Joaquin

**Comment by renatopp** [comment]
Hi Joaquin, thanks for this feedback, at maximum in this weekend (hopefully before that) I update this and review the @mfeurer  pull requests.
