### ISSUE TITLE
Bad @ATTRIBUTE format for "@ATTRIBUTE 0 {0,1} "

### ISSUE THREAD

**Issue by rustle1314** [renatopp/liac-arff#25]
In text mining task,we may want to design a feature, which indicates whether a document has the word "0". The feature in arff format is "@ATTRIBUTE 0 {0,1}".  When liac-arff parses it, we may encounter the "Bad @ATTRIBUTE format" exception. 

The similar problem occurs, when "@ATTRIBUTE _qacct {0,1}".

**Comment by renatopp** [comment]
Related to #24.

Thanks for the feedback, I'm closing this one because #24 also solves this problem.
