### ISSUE TITLE
Support for sparse data

### ISSUE THREAD

**Issue by lazywei** [renatopp/liac-arff#30]
Hi,

I think some data, e.g. the tmc2007, would be better loaded in as somewhat sparse format. How do you think?

**Comment by renatopp** [comment]
Would be really cool to have it. Can you make a pull request of this?

**Comment by mfeurer** [comment]
I was thinking about this, too. But I did not yet find an appropriate representation of sparse data which does not rely on an external library (scipy). You can then read the arff file in a data structure which is the input to a scipy.sparse matrix (https://github.com/mfeurer/liac-arff/commit/2a39b56b7affa0143b575dd814f796360bc50639). If you have some suggestions on how to go on from the code which is in my repo, I will be happy to do a pull request.

**Comment by lazywei** [comment]
How about using dictionary?
For example, in [libsvm](http://www.csie.ntu.edu.tw/~cjlin/libsvm/)'s python interface, they store sparse data in such format:

```
dense_fmt = [[0, 0, 1, 3, 0, 0, 5], ...]
sparse_fmt = [{2: 1, 3: 3, 6: 5}, ...]
```

How do you think?

**Comment by mfeurer** [comment]
That looks like a simple format. But I don't know how to go from that to something scikit-learn accepts.

What do you think about an argument to the `ArffDecoder` which determines the behaviour for sparse data? Right now this argument could take the values `dense`, `list_of_dicts`, `coo`.

**Comment by lazywei** [comment]
I think passing an argument for specifying the type is very helpful! That's exactly what I want!

**Comment by lazywei** [comment]
By the way, when using sparse format, would it be great if we turn nominal/category attributes to numeric (i.e., using integer: 0, 1, 2, ... to represent category) when returning?

**Comment by mfeurer** [comment]
The second thing is already implemented. I just checked and the documentation is not up to date. If you build the documentation on your computer, you will find an example of how to do that.

For the extra argument with the sparse data I would wait for the opinion of @renatopp before I will create a pull request.

**Comment by renatopp** [comment]
Hi!

The extra argument seems fine to me, but it should be well documented. What options we would add right now?

- dense: all values
- coo: a list of rows, a list of cols, and a list of data
- list_of_dicts: a list of dicts {col:value}
- anything else?

The option names would be these?

Another thing to consider is how dump would be made (in implementation level).

---

With this, may be the time to split the module into several files, what do you think?

**Comment by mfeurer** [comment]
Hi,

yes, documentation is important. I think the three choices `dense`, `coo` and `list_of_dicts` are fine for now.  If you have a look at my prototype implementation I had before this issue, you can see that it is quite hacky. Therefore I also propose to add a new object `data` (and subclasses for `dense`, `coo` and `list_of_dicts`), which avoids the if-statements like [here](https://github.com/mfeurer/liac-arff/commit/2a39b56b7affa0143b575dd814f796360bc50639#diff-5dd4108ea1a9c45dff3ae9653d45f74bR565). The user would not see this, but get a plain python object as a return value. On the implementation side, we would need an encoder for each of these objects. If this makes sense, I can start implementing this as soon as I find some time for it.

Best,
Matthias

**Comment by mfeurer** [comment]
Please have a look at my pull request.
