### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by ToshiyukiAndo** [renatopp/liac-arff#46]
I can't load arfffiles, error log is ↓

---

`>>>` import arff
`>>>` data = arff.load(open('sample.arff', 'rb'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/usr/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/arff.py", line 879, in load
    return_type=return_type)
  File "/Users/usr/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/arff.py", line 722, in decode
    matrix_type=return_type)
  File "/Users/usr/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/arff.py", line 636, in _decode
    row = row.strip(' \r\n')
TypeError: a bytes-like object is required, not 'str'
`>>>`

---

sample.arff is [from https://github.com/renatopp/arff-datasets](from https://github.com/renatopp/arff-datasets)

I think python's version deference makes this error, but sorry I don't know how to solve it. 
Please help me. Thank you.

**Comment by mfeurer** [comment]
Did you already try:
```
with open('sample.arff') as fh:
    arff.load(fh)
```
Like this the file isn't opened in binary mode which might cause the problem.

**Comment by ToshiyukiAndo** [comment]
Thanks your comment.
I tried it. Sorry 'fh' is invalid mode in my environment. Binary mode option is 'b' isn't it?

This is error log

-------------------------------------------

`>>>` import arff
`>>>` data = arff.load(open('sample.arff', 'fh'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid mode: 'fh'

**Comment by mfeurer** [comment]
You copied my example wrongly. The `fh` is not the open mode, but the file handle (thus `fh`) which is created by the context manager. You can read up on context managers [here](http://preshing.com/20110920/the-python-with-statement-by-example/). You're example should be:

    data = arff.load(open('sample.arff'))

does that work? 

An unrelated issue is that you don't close the file any more.

**Comment by ToshiyukiAndo** [comment]
Thanks your comment.
It work!!!
Thank you very much.

**Comment by aysebilgegunduz** [comment]
I've got the same problem and i've solved using 'r' instead of 'rb'. But your main example using and illustrating with 'rb'. So, i thought that i did something wrong in installation stage.
