### ISSUE TITLE
ImportError: No module named arff

### ISSUE THREAD

**Issue by robooo** [renatopp/liac-arff#53]
I'm getting this error on py2.7 or 3.6 on OS X
Installed via pip or easy_install
never had same issue with any python module (tried module arff too but same problem)
```
$ pip install liac-arff
Requirement already satisfied: liac-arff in /Library/Python/2.7/site-packages
```
```
$ python
Python 2.7.13 (default, Dec 18 2016, 07:03:34)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import arff
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named arff
```

**Comment by robooo** [comment]
Maybe the problem is because I have isntalled scipy before? 

`from scipy.io import arff` 
is working for me

**Comment by mfeurer** [comment]
Scipy and liac-arff should not conflict as the arff module in scipy lives in a different namespace. Could you please check that the file `arff.py` is in the site-packages directory and has the correct permissions? If that is all correct, you could also try uninstalling it, cloning it and installing it with `python setup.py install`.

Besides that I'm afraid that I'm no great help here as I've never encountered this problem and am not familiar with OSX.

**Comment by robooo** [comment]
problem was with permissions working now without problems (can call scipy arff and liac too)
recommend install with 
`python -m pip install liac-arff`
then it worked
