### ISSUE TITLE
Drop python2.6

### ISSUE THREAD

**Issue by mfeurer** [renatopp/liac-arff#57]
The support for python 2.6 seems to decline and for example sklearn decided to drop 2.6 support in the upcoming [0.19.X release](http://scikit-learn.org/dev/whats_new.html#version-0-18-1). Therefore, I propose to drop python 2.6 from the unit tests and not support it any longer.

**Comment by hugovk** [comment]
Looks like 2.6 was dropped in https://github.com/renatopp/liac-arff/pull/56/commits/6c19453b4b2e6e510fb07ccf6e846b6c41092777. Can this be closed?

**Comment by mfeurer** [comment]
I think so.
