### ISSUE TITLE
Trailing comment lines

### ISSUE THREAD

**Issue by joaquinvanschoren** [renatopp/liac-arff#61]
It seems that, whenever I use arff.dump(), it ends the output with 3 empty lines, like this:
```
125915,1,6250_weka.DecisionTable,0.97963,ok
125915,1,6378_weka.LogitBoost_DecisionStump,1.0,ok
% 
% 
% 
```

It that expected behavior or am I doing something wrong?

**Comment by mfeurer** [comment]
I don't know if this is to be expected, but it's in the code: https://github.com/renatopp/liac-arff/blob/master/arff.py#L867

**Comment by joaquinvanschoren** [comment]
Why is this necessary? Is this even valid arff?

**Comment by mfeurer** [comment]
I do not know why it is there. It was already there when I started using this project. The arff specs say that any line starting with an ampersand is a comment, so I think its fine.

**Comment by joaquinvanschoren** [comment]
Could we at least make it optional? It sometimes causes problems.

**Comment by mfeurer** [comment]
Sure, go ahead. However, when does it provide problems?

**Comment by joaquinvanschoren** [comment]
I remember I had to manually remove this for a few OpenML datasets.
I think it also creates issues when converting arff to csv
