### ISSUE TITLE
Efficiency improvements: what API needs to be stable?

### ISSUE THREAD

**Issue by jnothman** [renatopp/liac-arff#75]
If I am to offer changes improving loader efficiency, what guidelines do I need to adhere to in ensuring API stability? Is `load`/`loads`/`ArffDecoder.decode` the only real public interface for loading? Would restructuring the type conversion utilities be welcome?

**Comment by mfeurer** [comment]
> If I am to offer changes improving loader efficiency, what guidelines do I need to adhere to in ensuring API stability?

I think the only two somewhat complicated requirements are not adding any 3rd party dependencies and keeping support for the currently supported python versions. Other than that it should be fine if the unit tests still pass (assuming that you apply the same rigor as you do when working on scikit-learn) and the very simple dict format is returned.

> Is load/loads/ArffDecoder.decode the only real public interface for loading?

Yes.

> Would restructuring the type conversion utilities be welcome?

Yes. They are not facing the public so there's no need to keep them similar.

As especially the first requirement is somewhat odd (not adding any 3rd party libraries such as numpy and scipy), if you want to add 3rd party libraries, I'd be happy to discuss how to move to a new version 3 of liac-arff which is loosens this requirement.

Also, if you do larger changes, please let me know before as I will then prioritize finishing #67 to avoid merge conflicts.

**Comment by jnothman** [comment]
I have some changes almost ready to push...

**Comment by rth** [comment]
(Sorry if it's not the right issue to talk about benchmarks)

Regarding the previous comment, interestingly when loading MNIST on a computer without SSD it takes 93s with liac-arff and 27s with scipy's parser. So it's 40% slower that with an SSD (using the scipy parser as baseline in each case) -- I'm not quite sure why, but there might be some sub-optimal I/O reads..

**Comment by jnothman** [comment]
@rth, perhaps offer the benchmark script to the repo.​

**Comment by mfeurer** [comment]
@jnothman do you plan to do further optimizations or can this be closed?
