### ISSUE TITLE
Multi-line strings

### ISSUE THREAD

**Issue by jnothman** [renatopp/liac-arff#79]
What is the format for multiline strings? Is:
```
"one line
another line","another attribute"
```

correct?

Or

```
"one line\
another line","another attribute"
```
?

Or

```
"one line\nanother line","another attribute"
```
?

Or any of the above??

**Comment by mfeurer** [comment]
I can't find any mention of this in the [arff documentation](http://weka.wikispaces.com/ARFF%20%28stable%20version%29). Where did you find such files?

**Comment by jnothman** [comment]
I didn't find such files. But my background is in natural language
processing and I care very much that such data can be represented in a
resource like OpenML.​

**Comment by mfeurer** [comment]
I'm afraid that you either need to ask on the [mailing list](https://weka.wikispaces.com/Weka+Mailing+List) or check the [original arff parser](https://github.com/bnjmn/weka). Probably it works somehow, but is not documented.
