### ISSUE TITLE
dump, load and then dump fails

### ISSUE THREAD

**Issue by AndyNor** [renatopp/liac-arff#8]
The attributes types are being turned into strings when using dump() to ARFF
'attributes': [
	('local_hour', 'INTEGER'),
]
-->
@ATTRIBUTE 'local_hour' 'INTEGER'

When loading this back using load() it will be a the string 'INTEGER' and will miss the check "if type_values.upper() in DECODE_ARFF_TYPES" in the __decode_attribute(type_values) function. Basically comparing the string 'INTEGER' with the string INTEGER (same for the other types)

The type will thus always be treated as a list of options. This in turn will cause a new dump() of the data (without any modifications) to fail with "... was not listed as a valid nominal value for such types not being nominal.

**Comment by renatopp** [comment]
This is supposed to be fixed so I'm closing this. Feel free to open if needed.
