### ISSUE TITLE
Issue with separator space other than space

### ISSUE THREAD

**Issue by glemaitre** [renatopp/liac-arff#87]
We had a dataset with the character `\u3000` which is one of the separator space. The regular expression in the encoder only matches `\\` while it should use `\s` to match all possible separators and add quotes around the string to be compliant with the ARFF format.

I will open a PR to solve this issue.

**Comment by glemaitre** [comment]
> Are you using the character as a separator instead of a comma? Or inside a string field?

It is just a Japanese string with this space inside, so this is the second case.

> According to the unit test inside the PR as the second, but you would like it to be treated exactly like a regular space?

It should be treated as a separator space. ARFF mentions that you should quote this string then. No idea what WEKA is doing with those characters.

**Comment by glemaitre** [comment]
> It seems like WEKA doesn't bother about the japanese whitespace.

This is not only for Japanese whitespace. We also the have the "BeerAdvocate" which encode white space with `\xa0`. I might think that this is not something so infrequent.

> Therefore, I'm not sure if we need to take any action on this right now.

I strongly think that we should fix it now. Then, we can also point it to the WEKA implementation since they specified that string with spaces should be quoted.

**Comment by mfeurer** [comment]
No matter what WEKA does, adding those brackets should not hurt anyway. Let's add this.
