### ISSUE TITLE
ValueError: Matrix type arff.COO not supported.

### ISSUE THREAD

**Issue by tiagorochadealmeida** [renatopp/liac-arff#96]
Prof. Renato Pereira,

Tudo bem?

Eu me chamo Tiago e estou cursando especialização em IA no IESB, aqui em Brasília. 

Na matéria machine learning, conduzida pela profa. Letícia, tive o desafio de replicar o algoritmo Naives Bayes da base credit-g.arff do Weka para o Python.

Para cumprir esse desafio, encontrei o módulo https://pythonhosted.org/liac-arff/#, elaborado e gentilmente publicado por você. 

No entanto, me deparei com esse pequeno percalço ao utilizá-lo com google collab: 
![image](https://user-images.githubusercontent.com/40704409/57346796-4c0b0f80-7126-11e9-8a1e-05760b9ce433.png)

Então, resolvi pedir seu apoio para entender como posso superar esse desafio utilizando a estrutura de dados arff.

 Caso venha ser preciso, também me ofereço para colaborar na implementação de uma possível solução.

Att.

Tiago Rocha de Almeida

**Comment by jnothman** [comment]
The parameter is not expected as a string. Remove the quotes around arff.COO

**Comment by tiagorochadealmeida** [comment]
I just adjusted to arff.DENSE whithout quotes around so the error magically disappeared. I really thank you, @jnothman .
