### ISSUE TITLE
Bad @DATA instance format for UCI chronic kidney disease data

### ISSUE THREAD

**Issue by yli110-stat697** [renatopp/liac-arff#97]
Hi, I was trying to load the .arff file of the [UCI chronic kidney diease](https://archive.ics.uci.edu/ml/datasets/chronic_kidney_disease#) into python using 
`data = arff.loads(open('./Data/chronic_kidney_disease_full.arff'))
`
But I got the 'BadDataFormat' exception as a result
`BadDataFormat: Bad @DATA instance format in line 215: 26,70,1.015,0,4,?,normal,notpresent,notpresent,250,20,1.1,?,?,15.6,52,6900,6.0,no,yes,no,good,no,no,ckd,
`
Is there a way to fix this?

**Comment by jnothman** [comment]
It has a spurious trailing comma. It is, to my knowledge, invalid ARFF. Remove the trailing comma there and a few lines later.

**Comment by yli110-stat697** [comment]
I see. So There's no way to solve in using liac-arff package? In this case, do I have to convert .arff into csv to remove the trailing comma?

**Comment by jnothman** [comment]
You don't need to convert into CSV, you need to edit with a text editor

**Comment by yli110-stat697** [comment]
Got it! And it fixed my problem. The thing with this dataset is that it has so many bad instances when use liac-arff package. I just found that read_csv() can read .arff file too. Here's the link https://mclguide.readthedocs.io/en/latest/sklearn/preprocessing.html#chronic-kidney-disease

**Comment by hamidialii1990** [comment]
> Hi, I was trying to load the .arff file of the [UCI chronic kidney diease](https://archive.ics.uci.edu/ml/datasets/chronic_kidney_disease#) into python using `data = arff.loads(open('./Data/chronic_kidney_disease_full.arff')) ` But I got the 'BadDataFormat' exception as a result `BadDataFormat: Bad @DATA instance format in line 215: 26,70,1.015,0,4,?,normal,notpresent,notpresent,250,20,1.1,?,?,15.6,52,6900,6.0,no,yes,no,good,no,no,ckd, ` Is there a way to fix this?

Can you find any solution to your problem?
I get the same error also:

arff.BadDataFormat: Bad @DATA instance format in line 3096: free.fr,False,http://www.free.fr/adsl,2.0,5611,719,420.5199999999132,754.3740000000653,3627.99799

**Comment by yli110-stat697** [comment]
@hamidialii1990 sorry this was a while ago. Try the solution above, I think I fixed mine
